# Day 4 Assignment 4 — Customer, Product & Order Analysis

**Datasets:** `customers.csv`, `products.csv`, `orders.csv`

In [1]:
import pandas as pd
import numpy as np

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")

display(customers.head())
display(products.head())
display(orders.head())

  Customer_ID Customer_Name        City  Age  Gender
0      C00001    Customer_1       Delhi   56    Male
1      C00002    Customer_2      Mumbai   69  Female
2      C00003    Customer_3     Kolkata   46    Male
3      C00004    Customer_4  Coimbatore   32    Male
4      C00005    Customer_5     Chennai   60  Female

  Product_ID Product_Name Category     Price
0      P0001    Product_1   Sports  80239.48
1      P0002    Product_2   Beauty   7547.61
2      P0003    Product_3    Books  98690.00
3      P0004    Product_4   Beauty  77247.25
4      P0005    Product_5   Beauty  19951.70

  Order_ID Customer_ID Product_ID  Quantity           Order_Date
0  O000001      C00861      P0027         4  2025-01-01 00:00:00
1  O000002      C01295      P0047         3  2025-01-01 02:00:00
2  O000003      C01131      P0099         4  2025-01-01 04:00:00
3  O000004      C01096      P0006         1  2025-01-01 06:00:00
4  O000005      C01639      P0060         2  2025-01-01 08:00:00

## Q1. Load all three CSV files.

**Answer:**

In [2]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)

Customers: (3000, 5)
Products: (100, 4)
Orders: (15000, 5)

## Q2. Display the dimensions of each DataFrame.

**Answer:**

In [3]:
print("customers:", customers.shape)
print("products:", products.shape)
print("orders:", orders.shape)

customers: (3000, 5)
products: (100, 4)
orders: (15000, 5)

## Q3. Identify the columns in each dataset.

**Answer:**

In [4]:
for name, frame in [("Customers", customers), ("Products", products), ("Orders", orders)]:
    print(f"\n{name} columns:")
    print(frame.columns.tolist())

Customers columns:
['Customer_ID', 'Customer_Name', 'City', 'Age', 'Gender']

Products columns:
['Product_ID', 'Product_Name', 'Category', 'Price']

Orders columns:
['Order_ID', 'Customer_ID', 'Product_ID', 'Quantity', 'Order_Date']

## Q4. Identify the common columns between datasets.

**Answer:**

In [5]:
print("Customers ∩ Orders:", sorted(set(customers.columns) & set(orders.columns)))
print("Products ∩ Orders:", sorted(set(products.columns) & set(orders.columns)))
print("Customers ∩ Products:", sorted(set(customers.columns) & set(products.columns)))
print("All three:", sorted(set(customers.columns) & set(products.columns) & set(orders.columns)))

Customers ∩ Orders: ['Customer_ID']
Products ∩ Orders: ['Product_ID']
Customers ∩ Products: []
All three: []

## Q5. Determine how the three datasets are related.

**Answer:**

In [6]:
print("Orders links to Customers through Customer_ID.")
print("Orders links to Products through Product_ID.")
print("Each order therefore combines customer details and product details.")

Orders links to Customers through Customer_ID.
Orders links to Products through Product_ID.
Each order therefore combines customer details and product details.

## Q6. Check each DataFrame for missing values.

**Answer:**

In [7]:
for name, frame in [("Customers", customers), ("Products", products), ("Orders", orders)]:
    print(f"\n{name} missing values:")
    print(frame.isna().sum())

Customers missing values:
Customer_ID      0
Customer_Name    0
City             0
Age              0
Gender           0
dtype: int64

Products missing values:
Product_ID      0
Product_Name    0
Category        0
Price           0
dtype: int64

Orders missing values:
Order_ID       0
Customer_ID    0
Product_ID     0
Quantity       0
Order_Date     0
dtype: int64

## Q7. Check for duplicate records.

**Answer:**

In [8]:
for name, frame in [("Customers", customers), ("Products", products), ("Orders", orders)]:
    print(f"{name} duplicate rows:", frame.duplicated().sum())

Customers duplicate rows: 0
Products duplicate rows: 0
Orders duplicate rows: 0

## Q8. Check the validity of Customer_ID and Product_ID.

**Answer:**

In [9]:
print("Customer_ID unique:", customers["Customer_ID"].is_unique)
print("Product_ID unique:", products["Product_ID"].is_unique)
print("Customer_ID pattern valid:", customers["Customer_ID"].astype(str).str.fullmatch(r"C\d{5}").all())
print("Product_ID pattern valid:", products["Product_ID"].astype(str).str.fullmatch(r"P\d{4}").all())

Customer_ID unique: True
Product_ID unique: True
Customer_ID pattern valid: True
Product_ID pattern valid: True

## Q9. Convert Order_Date into datetime.

**Answer:**

In [10]:
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"], errors="coerce")
print("Order_Date dtype:", orders["Order_Date"].dtype)
print("Invalid dates:", orders["Order_Date"].isna().sum())

Order_Date dtype: datetime64[ns]
Invalid dates: 0

## Q10. Check whether every order corresponds to a valid customer.

**Answer:**

In [11]:
invalid_customers = (~orders["Customer_ID"].isin(customers["Customer_ID"])).sum()
print("Orders with invalid Customer_ID:", invalid_customers)
print("Every order has a valid customer:", invalid_customers == 0)

Orders with invalid Customer_ID: 0
Every order has a valid customer: True

## Q11. Check whether every order corresponds to a valid product.

**Answer:**

In [12]:
invalid_products = (~orders["Product_ID"].isin(products["Product_ID"])).sum()
print("Orders with invalid Product_ID:", invalid_products)
print("Every order has a valid product:", invalid_products == 0)

Orders with invalid Product_ID: 0
Every order has a valid product: True

## Q12. Merge orders with customers.

**Answer:**

In [13]:
orders_customers = orders.merge(customers, on="Customer_ID", how="left", validate="many_to_one")
print(orders_customers.shape)
display(orders_customers.head())

(15000, 9)

,Order_ID,Customer_ID,Product_ID,Quantity,Order_Date,Customer_Name,City,Age,Gender
0,O000001,C00861,P0027,4,2025-01-01 00:00:00,Customer_861,Kolkata,51,Female
1,O000002,C01295,P0047,3,2025-01-01 02:00:00,Customer_1295,Bangalore,43,Male
2,O000003,C01131,P0099,4,2025-01-01 04:00:00,Customer_1131,Pune,47,Female
3,O000004,C01096,P0006,1,2025-01-01 06:00:00,Customer_1096,Delhi,29,Male
4,O000005,C01639,P0060,2,2025-01-01 08:00:00,Customer_1639,Coimbatore,67,Female

## Q13. Merge the resulting DataFrame with products.

**Answer:**

In [14]:
consolidated = orders_customers.merge(products, on="Product_ID", how="left", validate="many_to_one")
print(consolidated.shape)
display(consolidated.head())

(15000, 12)

,Order_ID,Customer_ID,Product_ID,Quantity,Order_Date,Customer_Name,City,Age,Gender,Product_Name,Category,Price
0,O000001,C00861,P0027,4,2025-01-01 00:00:00,Customer_861,Kolkata,51,Female,Product_27,Sports,56171.59
1,O000002,C01295,P0047,3,2025-01-01 02:00:00,Customer_1295,Bangalore,43,Male,Product_47,Clothing,80831.23
2,O000003,C01131,P0099,4,2025-01-01 04:00:00,Customer_1131,Pune,47,Female,Product_99,Electronics,83546.72
3,O000004,C01096,P0006,1,2025-01-01 06:00:00,Customer_1096,Delhi,29,Male,Product_6,Clothing,651.66
4,O000005,C01639,P0060,2,2025-01-01 08:00:00,Customer_1639,Coimbatore,67,Female,Product_60,Sports,81819.68

## Q14. Create a final consolidated DataFrame.

**Answer:**

In [15]:
final_df = consolidated[[
    "Order_ID","Customer_ID","Customer_Name","City","Age","Gender",
    "Product_ID","Product_Name","Category","Price","Quantity","Order_Date"
]].copy()
display(final_df.head())
print("Final dimensions:", final_df.shape)

,Order_ID,Customer_ID,Customer_Name,City,Age,Gender,Product_ID,Product_Name,Category,Price,Quantity,Order_Date
0,O000001,C00861,Customer_861,Kolkata,51,Female,P0027,Product_27,Sports,56171.59,4,2025-01-01 00:00:00
1,O000002,C01295,Customer_1295,Bangalore,43,Male,P0047,Product_47,Clothing,80831.23,3,2025-01-01 02:00:00
2,O000003,C01131,Customer_1131,Pune,47,Female,P0099,Product_99,Electronics,83546.72,4,2025-01-01 04:00:00
3,O000004,C01096,Customer_1096,Delhi,29,Male,P0006,Product_6,Clothing,651.66,1,2025-01-01 06:00:00
4,O000005,C01639,Customer_1639,Coimbatore,67,Female,P0060,Product_60,Sports,81819.68,2,2025-01-01 08:00:00

Final dimensions: (15000, 12)

## Q15. Create Order_Value = Price × Quantity.

**Answer:**

In [16]:
final_df["Order_Value"] = final_df["Price"] * final_df["Quantity"]
display(final_df[["Order_ID","Price","Quantity","Order_Value"]].head())

  Order_ID     Price  Quantity  Order_Value
0  O000001  56171.59         4    224686.36
1  O000002  80831.23         3    242493.69
2  O000003  83546.72         4    334186.88
3  O000004    651.66         1       651.66
4  O000005  81819.68         2    163639.36

## Q16. Calculate total revenue.

**Answer:**

In [17]:
total_revenue = final_df["Order_Value"].sum()
print(f"Total revenue: ₹{total_revenue:,.2f}")

Total revenue: ₹2,233,171,871.30

## Q17. Calculate average order value.

**Answer:**

In [18]:
average_order_value = final_df["Order_Value"].mean()
print(f"Average order value: ₹{average_order_value:,.2f}")

Average order value: ₹148,878.12

## Q18. Find total revenue by product category.

**Answer:**

In [19]:
revenue_by_category = final_df.groupby("Category")["Order_Value"].sum().sort_values(ascending=False)
display(revenue_by_category.to_frame("Total_Revenue"))

                 Total_Revenue
Category
Sports            5.426713e+08
Clothing          4.261489e+08
Home Appliances   3.313110e+08
Electronics       3.312926e+08
Books             3.050563e+08
Beauty            2.966918e+08

## Q19. Find total revenue by city.

**Answer:**

In [20]:
revenue_by_city = final_df.groupby("City")["Order_Value"].sum().sort_values(ascending=False)
display(revenue_by_city.to_frame("Total_Revenue"))

            Total_Revenue
City
Kolkata      3.155500e+08
Hyderabad    2.932639e+08
Coimbatore   2.831225e+08
Mumbai       2.803566e+08
Pune         2.797505e+08
Delhi        2.654541e+08
Bangalore    2.637059e+08
Chennai      2.519685e+08

## Q20. Find the top 10 customers by spending.

**Answer:**

In [21]:
top10_customers = final_df.groupby(["Customer_ID","Customer_Name"])["Order_Value"].sum().sort_values(ascending=False).head(10)
display(top10_customers.to_frame("Total_Spending"))

                           Total_Spending
Customer_ID Customer_Name
C00019      Customer_19        3176078.87
C02897      Customer_2897      2528868.53
C01915      Customer_1915      2476932.74
C02709      Customer_2709      2400905.35
C00187      Customer_187       2394078.09
C00685      Customer_685       2352464.63
C01297      Customer_1297      2345815.39
C00259      Customer_259       2330070.43
C00921      Customer_921       2257528.60
C00271      Customer_271       2226186.64

## Q21. Find the top 10 products by revenue.

**Answer:**

In [22]:
top10_products = final_df.groupby(["Product_ID","Product_Name"])["Order_Value"].sum().sort_values(ascending=False).head(10)
display(top10_products.to_frame("Total_Revenue"))

                         Total_Revenue
Product_ID Product_Name
P0074      Product_74      47258003.68
P0088      Product_88      47213343.92
P0003      Product_3       47075130.00
P0046      Product_46      45000771.20
P0052      Product_52      44990386.56
P0073      Product_73      44897635.86
P0068      Product_68      44696626.32
P0038      Product_38      43658393.09
P0054      Product_54      40946977.89
P0050      Product_50      40756127.88

## Q22. Find the most frequently purchased product.

**Answer:**

In [23]:
product_frequency = final_df.groupby(["Product_ID","Product_Name"])["Quantity"].sum().sort_values(ascending=False)
print("Most frequently purchased product:")
display(product_frequency.head(1).to_frame("Total_Quantity"))
print("\nTop 10 by quantity:")
display(product_frequency.head(10).to_frame("Total_Quantity"))

Most frequently purchased product:

                         Total_Quantity
Product_ID Product_Name
P0015      Product_15               600

Top 10 by quantity:

                         Total_Quantity
Product_ID Product_Name
P0015      Product_15               600
P0081      Product_81               524
P0096      Product_96               519
P0010      Product_10               511
P0063      Product_63               509
P0050      Product_50               507
P0054      Product_54               507
P0052      Product_52               504
P0017      Product_17               504
P0036      Product_36               503

## Q23. Find the city with the highest number of customers.

**Answer:**

In [24]:
customer_count_by_city = customers["City"].value_counts()
display(customer_count_by_city.to_frame("Customer_Count"))
print("City with highest number of customers:", customer_count_by_city.idxmax())

            Customer_Count
City
Kolkata                412
Pune                   391
Coimbatore             387
Mumbai                 372
Hyderabad              372
Delhi                  364
Bangalore              360
Chennai                342

City with highest number of customers: Kolkata

## Q24. Find the city generating the highest revenue.

**Answer:**

In [25]:
print("City with highest revenue:", revenue_by_city.idxmax())
print(f"Revenue: ₹{revenue_by_city.max():,.2f}")

City with highest revenue: Kolkata
Revenue: ₹315,549,989.08

## Q25. Divide customers into age groups.

**Answer:**

In [26]:
customers["Age_Group"] = pd.cut(
    customers["Age"], bins=[17,30,45,60,np.inf],
    labels=["18–30","31–45","46–60","61+"]
)
print(customers["Age_Group"].value_counts().sort_index())

Age_Group
18–30    741
31–45    859
46–60    877
61+      523
Name: count, dtype: int64

## Q26. Calculate revenue generated by each age group.

**Answer:**

In [27]:
final_df["Age_Group"] = pd.cut(
    final_df["Age"], bins=[17,30,45,60,np.inf],
    labels=["18–30","31–45","46–60","61+"]
)
revenue_by_age_group = final_df.groupby("Age_Group", observed=False)["Order_Value"].sum()
display(revenue_by_age_group.to_frame("Revenue"))

                Revenue
Age_Group
18–30      5.586278e+08
31–45      6.223524e+08
46–60      6.599237e+08
61+        3.922680e+08

## Q27. Compare spending between male and female customers.

**Answer:**

In [28]:
gender_spending = final_df.groupby("Gender")["Order_Value"].agg(
    Total_Spending="sum",
    Average_Order_Value="mean"
).sort_values("Total_Spending", ascending=False)
display(gender_spending)
print("Higher total spending:", gender_spending["Total_Spending"].idxmax())

        Total_Spending  Average_Order_Value
Gender
Male      1.154200e+09        150639.544127
Female    1.078972e+09        147038.932161

Higher total spending: Male

## Q28. Identify high-value customers.

**Answer:**

In [29]:
# High-value customers are defined here as customers whose spending is above the median customer spending.
customer_spending = final_df.groupby(["Customer_ID","Customer_Name"])["Order_Value"].sum().sort_values(ascending=False)
high_value_threshold = customer_spending.median()
high_value_customers = customer_spending[customer_spending > high_value_threshold]
print(f"High-value threshold (median spending): ₹{high_value_threshold:,.2f}")
print("Number of high-value customers:", len(high_value_customers))
display(high_value_customers.head(10).to_frame("Total_Spending"))

High-value threshold (median spending): ₹689,917.34
Number of high-value customers: 1488

                           Total_Spending
Customer_ID Customer_Name
C00019      Customer_19        3176078.87
C02897      Customer_2897      2528868.53
C01915      Customer_1915      2476932.74
C02709      Customer_2709      2400905.35
C00187      Customer_187       2394078.09
C00685      Customer_685       2352464.63
C01297      Customer_1297      2345815.39
C00259      Customer_259       2330070.43
C00921      Customer_921       2257528.60
C00271      Customer_271       2226186.64

## Q29. Determine the percentage of customers who have placed more than one order.

**Answer:**

In [30]:
orders_per_customer = orders["Customer_ID"].value_counts()
repeat_customers = (orders_per_customer > 1).sum()
percentage_repeat = repeat_customers / len(customers) * 100
print("Customers with more than one order:", repeat_customers)
print(f"Percentage of customers with more than one order: {percentage_repeat:.2f}%")

Customers with more than one order: 2881
Percentage of customers with more than one order: 96.03%

## Q30. Create a customer spending ranking.

**Answer:**

In [31]:
customer_ranking = final_df.groupby(["Customer_ID","Customer_Name"])["Order_Value"].sum().sort_values(
    ascending=False
).reset_index(name="Total_Spending")
customer_ranking["Rank"] = customer_ranking["Total_Spending"].rank(method="min", ascending=False).astype(int)
customer_ranking = customer_ranking[["Rank","Customer_ID","Customer_Name","Total_Spending"]]
display(customer_ranking.head(20))

    Rank Customer_ID  Customer_Name  Total_Spending
0      1      C00019    Customer_19      3176078.87
1      2      C02897  Customer_2897      2528868.53
2      3      C01915  Customer_1915      2476932.74
3      4      C02709  Customer_2709      2400905.35
4      5      C00187   Customer_187      2394078.09
5      6      C00685   Customer_685      2352464.63
6      7      C01297  Customer_1297      2345815.39
7      8      C00259   Customer_259      2330070.43
8      9      C00921   Customer_921      2257528.60
9     10      C00271   Customer_271      2226186.64
10    11      C00874   Customer_874      2226100.84
11    12      C02512  Customer_2512      2198748.65
12    13      C01470  Customer_1470      2161834.00
13    14      C01204  Customer_1204      2138897.58
14    15      C02988  Customer_2988      2105275.02
15    16      C02281  Customer_2281      2092954.47
16    17      C01756  Customer_1756      2075097.31
17    18      C01130  Customer_1130      2066469.96
18    19      C01142  Customer_1142      2050412.31
19    20      C02551  Customer_2551      2034948.13

## Q31. Identify the top 10% of customers based on total spending.

**Answer:**

In [32]:
n_top_10 = int(np.ceil(len(customer_ranking) * 0.10))
top_10_percent_customers = customer_ranking.head(n_top_10).copy()
print("Number of customers in top 10%:", n_top_10)
print(f"Spending by top 10%: ₹{top_10_percent_customers['Total_Spending'].sum():,.2f}")
display(top_10_percent_customers.head(20))

Number of customers in top 10%: 298
Spending by top 10%: ₹479,774,919.18

    Rank Customer_ID  Customer_Name  Total_Spending
0      1      C00019    Customer_19      3176078.87
1      2      C02897  Customer_2897      2528868.53
2      3      C01915  Customer_1915      2476932.74
3      4      C02709  Customer_2709      2400905.35
4      5      C00187   Customer_187      2394078.09
5      6      C00685   Customer_685      2352464.63
6      7      C01297  Customer_1297      2345815.39
7      8      C00259   Customer_259      2330070.43
8      9      C00921   Customer_921      2257528.60
9     10      C00271   Customer_271      2226186.64
10    11      C00874   Customer_874      2226100.84
11    12      C02512  Customer_2512      2198748.65
12    13      C01470  Customer_1470      2161834.00
13    14      C01204  Customer_1204      2138897.58
14    15      C02988  Customer_2988      2105275.02
15    16      C02281  Customer_2281      2092954.47
16    17      C01756  Customer_1756      2075097.31
17    18      C01130  Customer_1130      2066469.96
18    19      C01142  Customer_1142      2050412.31
19    20      C02551  Customer_2551      2034948.13

## Q32. Find the most profitable product category for each city.

**Answer:**

In [33]:
city_category_revenue = final_df.groupby(["City","Category"])["Order_Value"].sum().reset_index()
idx = city_category_revenue.groupby("City")["Order_Value"].idxmax()
most_profitable_category_by_city = city_category_revenue.loc[idx].sort_values("City").reset_index(drop=True)
display(most_profitable_category_by_city)

         City Category  Order_Value
0   Bangalore   Sports  71326795.18
1     Chennai   Sports  68298118.24
2  Coimbatore   Sports  69553033.93
3       Delhi   Sports  61019537.25
4   Hyderabad   Sports  65716665.57
5     Kolkata   Sports  71822933.47
6      Mumbai   Sports  63898188.25
7        Pune   Sports  71035989.75

## Q33. Find the most popular product in each category.

**Answer:**

In [34]:
category_product_quantity = final_df.groupby(["Category","Product_Name"])["Quantity"].sum().reset_index()
idx = category_product_quantity.groupby("Category")["Quantity"].idxmax()
most_popular_product = category_product_quantity.loc[idx].sort_values("Category").reset_index(drop=True)
display(most_popular_product)

          Category Product_Name  Quantity
0           Beauty   Product_10       511
1            Books   Product_63       509
2         Clothing   Product_15       600
3      Electronics   Product_54       507
4  Home Appliances   Product_17       504
5           Sports   Product_96       519

## Q34. Calculate monthly revenue.

**Answer:**

In [35]:
monthly_revenue = final_df.set_index("Order_Date").resample("MS")["Order_Value"].sum()
display(monthly_revenue.to_frame("Monthly_Revenue"))

            Monthly_Revenue
Order_Date
2025-01-01      53361220.93
2025-02-01      52963079.79
2025-03-01      56233288.12
2025-04-01      50923849.46
2025-05-01      57301343.61
2025-06-01      56460489.60
2025-07-01      54157148.69
2025-08-01      57144165.05
2025-09-01      53352193.95
2025-10-01      56630127.31
2025-11-01      59276825.16
2025-12-01      59630660.46
2026-01-01      56260151.26
2026-02-01      47689351.93
2026-03-01      55497703.15
2026-04-01      51306881.32
2026-05-01      51823753.71
2026-06-01      51618514.74
2026-07-01      54128777.26
2026-08-01      57438462.80
2026-09-01      55460907.01
2026-10-01      57171177.74
2026-11-01      56875351.32
2026-12-01      52435333.48
2027-01-01      56072466.01
2027-02-01      48032412.73
2027-03-01      51740476.06
2027-04-01      51673329.49
2027-05-01      55972559.14
2027-06-01      55791489.47
2027-07-01      57720544.86
2027-08-01      55334425.53
2027-09-01      53134726.53
2027-10-01      53646489.78
2027-11-01      53680865.96
2027-12-01      55292934.52
2028-01-01      52205366.58
2028-02-01      48474671.11
2028-03-01      55381632.73
2028-04-01      51636778.77
2028-05-01      57204319.10
2028-06-01       5035625.08

## Q35. Identify the month with the highest revenue.

**Answer:**

In [36]:
best_month = monthly_revenue.idxmax()
best_month_revenue = monthly_revenue.max()
print("Month with highest revenue:", best_month.strftime("%B %Y"))
print(f"Highest monthly revenue: ₹{best_month_revenue:,.2f}")

Month with highest revenue: December 2025
Highest monthly revenue: ₹59,630,660.46