# Day 4 Assignment 1 — Patient Clinical Data Analysis

**Dataset:** `patient_clinical_data_raw.csv`

In [3]:
import pandas as pd
import numpy as np

# Load the raw dataset
df = pd.read_csv("patient_clinical_data_raw.csv")
df.head()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No
1,P05835,NaN,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No
3,P08789,NaN,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No

## Q1. Load the dataset into a Pandas DataFrame.

**Answer:**

In [4]:
df = pd.read_csv("patient_clinical_data_raw.csv")
print(df.head())

  Patient_ID   Age  Gender        Department Blood_Pressure  Heart_Rate  \
0     P07402  58.0  Female       Orthopedics         119/73        64.0
1     P05835   NaN  Female  General Medicine         107/91        62.0
2     P02123  47.0    Male       Orthopedics         148/98        83.0
3     P08789   NaN    Male          Oncology         115/84        89.0
4     P00305  47.0  Female       Orthopedics         128/62        77.0

   Temperature  Cholesterol  Glucose      Diagnosis Admission_Type  \
0        100.0        197.0     60.0  Heart Disease       Referral
1         98.8        215.0     92.0       Migraine       Referral
2         96.0        196.0    133.0       Fracture        Routine
3        100.1        224.0    119.0   Hypertension       Referral
4        100.3        184.0    113.0   Hypertension      Emergency

   Length_of_Stay  Treatment_Cost Readmission
0               5        91183.33          No
1               5        71104.32          No
2               7       135197.73          No
3               6       146462.06          No
4               6        57510.66          No

## Q2. Display the first 10 and last 10 records.

**Answer:**

In [5]:
print("First 10 records:")
display(df.head(10))

print("Last 10 records:")
display(df.tail(10))

First 10 records:

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No
1,P05835,NaN,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No
3,P08789,NaN,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No
5,P02532,31.0,Female,Oncology,104/85,99.0,96.3,196.0,86.0,Hypertension,Routine,5,128417.99,Yes
6,P02996,49.0,MALE,Neurology,118/83,108.0,99.4,192.0,166.0,Heart Disease,Routine,7,106428.84,No
7,P07660,32.0,Female,Pediatrics,122/89,64.0,97.9,186.0,101.0,Cancer,Routine,5,126644.27,No
8,P08225,64.0,Male,Neurology,161/100,61.0,98.5,178.0,85.0,Cancer,Emergency,7,76285.34,No
9,P04449,56.0,Male,General Medicine,102/76,83.0,97.9,263.0,147.0,Migraine,Routine,6,150822.91,No

Last 10 records:

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
10090,P08323,80.0,Female,cardiology,143/68,95.0,98.5,209.0,96.0,Migraine,Referral,6,113362.17,No
10091,P05579,NaN,Male,Orthopedics,130/70,55.0,98.6,210.0,136.0,Migraine,Emergency,6,68281.49,No
10092,P04427,54.0,Female,Neurology,126/93,82.0,98.5,168.0,147.0,Asthma,Referral,4,106702.38,No
10093,P00467,59.0,Female,Cardiology,126/85,81.0,98.4,212.0,150.0,Heart Disease,Routine,6,62179.59,No
10094,P06266,50.0,Female,Pediatrics,123/93,82.0,98.7,185.0,60.0,Infection,Routine,6,108423.54,Yes
10095,P05735,37.0,Female,cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,NaN,Infection,Routine,5,103698.89,No
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No

## Q3. Find the number of rows and columns.

**Answer:**

In [6]:
rows, columns = df.shape
print("Rows:", rows)
print("Columns:", columns)

Rows: 10100
Columns: 14

## Q4. Display the column names and their data types.

**Answer:**

In [7]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Column names:
['Patient_ID', 'Age', 'Gender', 'Department', 'Blood_Pressure', 'Heart_Rate', 'Temperature', 'Cholesterol', 'Glucose', 'Diagnosis', 'Admission_Type', 'Length_of_Stay', 'Treatment_Cost', 'Readmission']

Data types:
Patient_ID         object
Age               float64
Gender             object
Department         object
Blood_Pressure     object
Heart_Rate        float64
Temperature       float64
Cholesterol       float64
Glucose           float64
Diagnosis          object
Admission_Type     object
Length_of_Stay      int64
Treatment_Cost    float64
Readmission        object
dtype: object

## Q5. Generate a statistical summary of the numerical columns.

**Answer:**

In [8]:
display(df.describe(include="number"))

,Age,Heart_Rate,Temperature,Cholesterol,Glucose,Length_of_Stay,Treatment_Cost
count,9798.000000,9798.000000,9796.000000,9797.000000,9798.000000,10100.000000,10100.000000
mean,47.418249,77.927740,98.399490,195.187098,106.199939,5.033960,100538.421836
std,18.021377,11.914117,1.199324,34.777238,28.656813,1.996912,42516.545663
min,-5.000000,45.000000,95.000000,100.000000,60.000000,1.000000,13492.020000
25%,35.000000,70.000000,97.600000,172.000000,85.000000,4.000000,68704.152500
50%,47.000000,78.000000,98.400000,195.000000,105.000000,5.000000,94104.265000
75%,60.000000,86.000000,99.200000,219.000000,126.000000,6.000000,125074.220000
max,150.000000,122.000000,102.900000,326.000000,209.000000,14.000000,315212.620000

## Q6. Identify the number of unique values in each column.

**Answer:**

In [9]:
print(df.nunique(dropna=False))

Patient_ID        10000
Age                  93
Gender                5
Department            9
Blood_Pressure     3645
Heart_Rate           76
Temperature          77
Cholesterol         207
Glucose             146
Diagnosis             8
Admission_Type        3
Length_of_Stay       14
Treatment_Cost     9998
Readmission           2
dtype: int64

## Q7. Identify all columns containing missing values.

**Answer:**

In [10]:
missing_columns = df.columns[df.isna().any()].tolist()
print("Columns containing missing values:", missing_columns)

Columns containing missing values: ['Age', 'Heart_Rate', 'Temperature', 'Cholesterol', 'Glucose']

## Q8. Calculate the percentage of missing values in each column.

**Answer:**

In [11]:
missing_percentage = (df.isna().mean() * 100).sort_values(ascending=False)
print(missing_percentage)

Temperature       3.009901
Cholesterol       3.000000
Age               2.990099
Glucose           2.990099
Heart_Rate        2.990099
Patient_ID        0.000000
Blood_Pressure    0.000000
Department        0.000000
Gender            0.000000
Diagnosis         0.000000
Admission_Type    0.000000
Length_of_Stay    0.000000
Treatment_Cost    0.000000
Readmission       0.000000
dtype: float64

## Q9. Handle missing values in the numerical columns appropriately.

**Answer:**

In [12]:
numeric_columns = df.select_dtypes(include="number").columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

print("Missing numerical values after handling:")
print(df[numeric_columns].isna().sum())

Missing numerical values after handling:
Age               0
Heart_Rate        0
Temperature       0
Cholesterol       0
Glucose           0
Length_of_Stay    0
Treatment_Cost    0
dtype: int64

## Q10. Identify and remove duplicate records.

**Answer:**

In [13]:
duplicate_count = df.duplicated().sum()
print("Duplicate records:", duplicate_count)

df = df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

Duplicate records: 100
Shape after removing duplicates: (10000, 14)

## Q11. Check the Age column for invalid values.

**Answer:**

In [14]:
if "Age" in df.columns:
    print("Minimum Age:", df["Age"].min())
    print("Maximum Age:", df["Age"].max())
    print("Invalid age records:")
    display(df[(df["Age"] < 0) | (df["Age"] > 120)])
else:
    print("Age column not found.")

Minimum Age: -5.0
Maximum Age: 150.0
Invalid age records:

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
39,P00304,150.0,Female,General Medicine,116/93,94.0,98.5,207.0,152.0,Migraine,Referral,5,81852.40,No
399,P07151,150.0,Male,Neurology,141/77,68.0,98.4,195.0,85.0,Cancer,Routine,4,69542.41,No
682,P00684,-5.0,Male,General Medicine,117/77,55.0,98.5,146.0,154.0,Infection,Routine,2,52628.80,No
1214,P06801,-5.0,Male,General Medicine,145/64,90.0,98.7,157.0,162.0,Cancer,Referral,4,78841.67,No
1413,P08175,-5.0,Male,Orthopedics,127/92,74.0,98.4,189.0,99.0,Diabetes,Emergency,3,68268.64,Yes
1612,P00555,150.0,Female,Pediatrics,129/54,53.0,97.6,223.0,132.0,Heart Disease,Routine,5,85293.98,No
2090,P01771,-5.0,Female,Cardiology,134/77,77.0,100.0,189.0,131.0,Asthma,Referral,8,95832.96,No
2454,P02920,-5.0,Male,Cardiology,157/76,86.0,98.7,139.0,82.0,Heart Disease,Routine,3,42391.19,Yes
3774,P09773,-5.0,Female,Cardiology,118/62,97.0,98.4,171.0,124.0,Cancer,Emergency,10,162966.28,No
4311,P02156,-5.0,Male,Cardiology,153/78,63.0,98.0,166.0,60.0,Hypertension,Routine,7,186112.26,Yes
5834,P08060,-5.0,Male,Cardiology,149/92,92.0,99.6,201.0,134.0,Heart Disease,Emergency,7,197002.43,No
6147,P06021,-5.0,Male,Pediatrics,107/82,84.0,98.8,178.0,111.0,Infection,Routine,4,116787.01,No
6691,P00116,150.0,Male,Oncology,117/66,79.0,98.7,189.0,187.0,Asthma,Referral,5,135720.88,No
8487,P03639,-5.0,Male,Oncology,139/74,57.0,99.9,206.0,105.0,Infection,Emergency,6,146178.40,No
8981,P05183,150.0,Female,Pediatrics,120/73,86.0,99.1,186.0,64.0,Infection,Routine,9,142863.74,No

## Q12. Correct or handle patients whose age is outside a reasonable range.

**Answer:**

In [15]:
if "Age" in df.columns:
    invalid_age = (df["Age"] < 0) | (df["Age"] > 120)
    print("Invalid ages before correction:", invalid_age.sum())

    # Treat invalid ages as missing, then fill with the median age.
    df.loc[invalid_age, "Age"] = np.nan
    df["Age"] = df["Age"].fillna(df["Age"].median())

    print("Invalid ages after correction:", ((df["Age"] < 0) | (df["Age"] > 120)).sum())

Invalid ages before correction: 15
Invalid ages after correction: 0

## Q13. Identify inconsistent values in categorical columns such as Gender and Department.

**Answer:**

In [16]:
categorical_columns = df.select_dtypes(include=["object", "category"]).columns

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].dropna().astype(str).value_counts())

Patient_ID:
Patient_ID
P06421    1
P01185    1
P04556    1
P03386    1
P06397    1
         ..
P00305    1
P08789    1
P02123    1
P05835    1
P07402    1
Name: count, Length: 10000, dtype: int64

Gender:
Gender
Male        4920
Female      4780
MALE         100
male         100
 FEMALE      100
Name: count, dtype: int64

Department:
Department
Oncology            1662
Orthopedics         1644
Pediatrics          1614
Neurology           1612
General Medicine    1607
Cardiology          1561
 CARDIOLOGY          100
cardiology           100
neurology            100
Name: count, dtype: int64

Blood_Pressure:
Blood_Pressure
125/78     13
127/77     12
128/76     12
121/85     12
123/72     12
           ..
177/73      1
93/52       1
170/77      1
141/102     1
134/96      1
Name: count, Length: 3645, dtype: int64

Diagnosis:
Diagnosis
Cancer           1279
Diabetes         1275
Asthma           1274
Infection        1272
Hypertension     1249
Migraine         1243
Fracture         1208
Heart Disease    1200
Name: count, dtype: int64

Admission_Type:
Admission_Type
Routine      4414
Emergency    3530
Referral     2056
Name: count, dtype: int64

Readmission:
Readmission
No     8146
Yes    1854
Name: count, dtype: int64

## Q14. Standardize these categorical values.

**Answer:**

In [17]:
# Standardize string-based categorical columns by trimming whitespace
# and applying consistent capitalization.
for col in categorical_columns:
    df[col] = df[col].apply(
        lambda x: x.strip().title() if isinstance(x, str) else x
    )

print("Categorical values standardized.")

Categorical values standardized.

## Q15. Create Age_Group using the specified ranges.

**Answer:**

In [18]:
bins = [-np.inf, 17, 40, 60, np.inf]
labels = ["Child", "Young Adult", "Middle Age", "Senior"]

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

display(df[["Age", "Age_Group"]].head())

    Age   Age_Group
0  58.0  Middle Age
1  47.0  Middle Age
2  47.0  Middle Age
3  47.0  Middle Age
4  47.0  Middle Age

## Q16. Separate Blood_Pressure into Systolic and Diastolic columns.

**Answer:**

In [19]:
if "Blood_Pressure" in df.columns:
    bp = df["Blood_Pressure"].astype(str).str.extract(
        r"(\d+)\s*/\s*(\d+)"
    )
    df["Systolic"] = pd.to_numeric(bp[0], errors="coerce")
    df["Diastolic"] = pd.to_numeric(bp[1], errors="coerce")
else:
    print("Blood_Pressure column not found.")

display(df.head())

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No,Middle Age,119,73
1,P05835,47.0,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No,Middle Age,107,91
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No,Middle Age,148,98
3,P08789,47.0,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No,Middle Age,115,84
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No,Middle Age,128,62

## Q17. Create a High_Risk column based on suitable clinical conditions.

**Answer:**

In [20]:
# A patient is marked high-risk if any of the following are present:
# high glucose, high cholesterol, high heart rate, or age above 60.
# Thresholds are explicitly defined here so the rule is reproducible.
conditions = []

if "Glucose" in df.columns:
    conditions.append(df["Glucose"] > 140)
if "Cholesterol" in df.columns:
    conditions.append(df["Cholesterol"] > 240)
if "Heart_Rate" in df.columns:
    conditions.append(df["Heart_Rate"] > 100)
if "Age" in df.columns:
    conditions.append(df["Age"] > 60)

if conditions:
    df["High_Risk"] = np.logical_or.reduce(conditions)
else:
    df["High_Risk"] = False

display(df[["High_Risk"]].head())

   High_Risk
0      False
1      False
2      False
3      False
4      False

## Q18. Create Cost_Per_Day using treatment cost and length of stay.

**Answer:**

In [21]:
cost_col = next((c for c in ["Treatment_Cost", "Treatment Cost", "TreatmentCost"] if c in df.columns), None)
stay_col = next((c for c in ["Length_of_Stay", "Length of Stay", "LengthOfStay"] if c in df.columns), None)

if cost_col and stay_col:
    df["Cost_Per_Day"] = df[cost_col] / df[stay_col].replace(0, np.nan)
    df["Cost_Per_Day"] = df["Cost_Per_Day"].fillna(0)
    display(df[[cost_col, stay_col, "Cost_Per_Day"]].head())
else:
    print("Treatment cost or length-of-stay column was not found.")

   Treatment_Cost  Length_of_Stay  Cost_Per_Day
0        91183.33               5  18236.666000
1        71104.32               5  14220.864000
2       135197.73               7  19313.961429
3       146462.06               6  24410.343333
4        57510.66               6   9585.110000

## Q19. Calculate the average age of patients.

**Answer:**

In [22]:
print("Average age:", df["Age"].mean())

Average age: 47.3914

## Q20. Find the number of patients in each department.

**Answer:**

In [23]:
print(df["Department"].value_counts(dropna=False))

Department
Cardiology          1761
Neurology           1712
Oncology            1662
Orthopedics         1644
Pediatrics          1614
General Medicine    1607
Name: count, dtype: int64

## Q21. Calculate the average treatment cost for each department.

**Answer:**

In [24]:
cost_col = next((c for c in ["Treatment_Cost", "Treatment Cost", "TreatmentCost"] if c in df.columns), None)

if cost_col:
    print(df.groupby("Department")[cost_col].mean())
else:
    print("Treatment cost column was not found.")

Department
Cardiology          102040.799086
General Medicine    100711.121568
Neurology           101224.787389
Oncology            100039.380927
Orthopedics         100302.539605
Pediatrics           99036.600929
Name: Treatment_Cost, dtype: float64

## Q22. Find the average length of stay for each diagnosis.

**Answer:**

In [25]:
stay_col = next((c for c in ["Length_of_Stay", "Length of Stay", "LengthOfStay"] if c in df.columns), None)

if stay_col:
    print(df.groupby("Diagnosis")[stay_col].mean())
else:
    print("Length-of-stay column was not found.")

Diagnosis
Asthma           4.993721
Cancer           4.995309
Diabetes         5.080000
Fracture         5.030629
Heart Disease    5.003333
Hypertension     5.100881
Infection        5.023585
Migraine         5.045857
Name: Length_of_Stay, dtype: float64

## Q23. Identify the top 10 patients with the highest treatment cost.

**Answer:**

In [26]:
cost_col = next((c for c in ["Treatment_Cost", "Treatment Cost", "TreatmentCost"] if c in df.columns), None)

if cost_col:
    display(df.nlargest(10, cost_col))
else:
    print("Treatment cost column was not found.")

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
1785,P09106,41.0,Male,Neurology,117/73,88.0,98.1,186.0,121.0,Infection,Routine,12,315212.62,Yes,Middle Age,117,73,False,26267.718333
9966,P01900,42.0,Female,Orthopedics,131/84,78.0,97.0,175.0,77.0,Infection,Referral,11,288519.47,No,Middle Age,131,84,False,26229.042727
4796,P06995,36.0,Male,Oncology,150/78,80.0,95.0,200.0,108.0,Asthma,Routine,12,286702.48,Yes,Young Adult,150,78,False,23891.873333
7306,P09616,55.0,Male,Neurology,137/76,66.0,96.1,191.0,98.0,Cancer,Emergency,11,285387.70,No,Middle Age,137,76,False,25944.336364
3659,P07933,44.0,Female,Oncology,122/69,87.0,98.4,244.0,108.0,Fracture,Emergency,12,278888.31,No,Middle Age,122,69,True,23240.692500
1679,P03835,30.0,Female,Neurology,120/86,66.0,100.2,198.0,81.0,Hypertension,Referral,10,273491.74,No,Young Adult,120,86,False,27349.174000
1587,P01350,43.0,Male,Pediatrics,140/89,80.0,98.3,180.0,108.0,Hypertension,Routine,11,273458.79,No,Middle Age,140,89,False,24859.890000
4683,P01358,55.0,Male,Orthopedics,85/54,59.0,98.3,208.0,60.0,Infection,Referral,10,273007.12,No,Middle Age,85,54,False,27300.712000
4735,P08810,61.0,Male,Pediatrics,80/70,63.0,97.0,171.0,101.0,Diabetes,Emergency,11,271716.86,No,Senior,80,70,True,24701.532727
924,P07801,32.0,Male,Neurology,138/73,61.0,98.7,209.0,130.0,Heart Disease,Emergency,10,269594.52,No,Young Adult,138,73,False,26959.452000

## Q24. Find the department with the highest average treatment cost.

**Answer:**

In [27]:
cost_col = next((c for c in ["Treatment_Cost", "Treatment Cost", "TreatmentCost"] if c in df.columns), None)

if cost_col:
    department_avg_cost = df.groupby("Department")[cost_col].mean()
    print("Department with highest average treatment cost:",
          department_avg_cost.idxmax())
    print("Average treatment cost:", department_avg_cost.max())
else:
    print("Treatment cost column was not found.")

Department with highest average treatment cost: Cardiology
Average treatment cost: 102040.79908574674

## Q25. Calculate the percentage of patients who were readmitted.

**Answer:**

In [28]:
readmit_col = next((c for c in ["Readmitted", "Readmission", "Readmitted_Status"] if c in df.columns), None)

if readmit_col:
    values = df[readmit_col].astype(str).str.strip().str.lower()
    yes_values = {"yes", "y", "1", "true", "readmitted"}
    readmitted_percentage = values.isin(yes_values).mean() * 100
    print("Readmitted percentage:", readmitted_percentage)
else:
    print("Readmission column was not found.")

Readmitted percentage: 18.54

## Q26. Compare readmission rates across departments.

**Answer:**

In [29]:
readmit_col = next((c for c in ["Readmitted", "Readmission", "Readmitted_Status"] if c in df.columns), None)

if readmit_col:
    temp = df.copy()
    values = temp[readmit_col].astype(str).str.strip().str.lower()
    temp["_readmitted_flag"] = values.isin({"yes", "y", "1", "true", "readmitted"})
    rates = temp.groupby("Department")["_readmitted_flag"].mean() * 100
    print(rates.sort_values(ascending=False))
else:
    print("Readmission column was not found.")

Department
Neurology           20.560748
Cardiology          19.875071
Pediatrics          18.525403
Orthopedics         18.369830
General Medicine    17.797138
Oncology            15.944645
Name: _readmitted_flag, dtype: float64

## Q27. Find the average cholesterol and glucose level by diagnosis.

**Answer:**

In [30]:
available = [c for c in ["Cholesterol", "Glucose"] if c in df.columns]

if available:
    display(df.groupby("Diagnosis")[available].mean())
else:
    print("Cholesterol/Glucose columns were not found.")

               Cholesterol     Glucose
Diagnosis
Asthma          197.087127  105.994505
Cancer          195.383112  104.727131
Diabetes        195.018039  107.374902
Fracture        194.125828  105.047185
Heart Disease   196.663333  107.385833
Hypertension    194.117694  107.273819
Infection       193.593553  105.386792
Migraine        195.653258  106.185036

## Q28. Identify patients with high glucose, high cholesterol, and high heart rate.

**Answer:**

In [31]:
conditions = {}

if "Glucose" in df.columns:
    conditions["High Glucose"] = df["Glucose"] > 140

if "Cholesterol" in df.columns:
    conditions["High Cholesterol"] = df["Cholesterol"] > 240

if "Heart_Rate" in df.columns:
    conditions["High Heart Rate"] = df["Heart_Rate"] > 100

for label, condition in conditions.items():
    print("\n" + label)
    display(df[condition])

High Glucose

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
6,P02996,49.0,Male,Neurology,118/83,108.0,99.4,192.0,166.0,Heart Disease,Routine,7,106428.84,No,Middle Age,118,83,True,15204.120000
9,P04449,56.0,Male,General Medicine,102/76,83.0,97.9,263.0,147.0,Migraine,Routine,6,150822.91,No,Middle Age,102,76,True,25137.151667
34,P09850,60.0,Female,Cardiology,130/71,71.0,98.9,214.0,159.0,Heart Disease,Emergency,6,81510.78,No,Middle Age,130,71,True,13585.130000
39,P00304,47.0,Female,General Medicine,116/93,94.0,98.5,207.0,152.0,Migraine,Referral,5,81852.40,No,Middle Age,116,93,True,16370.480000
44,P07289,63.0,Female,Oncology,105/67,73.0,97.5,224.0,146.0,Asthma,Emergency,3,52880.24,Yes,Senior,105,67,True,17626.746667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9947,P08227,40.0,Male,Neurology,101/85,78.0,97.7,280.0,146.0,Heart Disease,Routine,2,36953.04,Yes,Young Adult,101,85,True,18476.520000
9950,P07100,22.0,Male,Orthopedics,126/69,80.0,98.4,222.0,144.0,Heart Disease,Referral,2,56892.63,No,Young Adult,126,69,True,28446.315000
9971,P09999,56.0,Female,Neurology,111/88,70.0,98.9,165.0,144.0,Cancer,Emergency,2,29228.17,Yes,Middle Age,111,88,True,14614.085000
9992,P04427,54.0,Female,Neurology,126/93,82.0,98.5,168.0,147.0,Asthma,Referral,4,106702.38,No,Middle Age,126,93,True,26675.595000
9993,P00467,59.0,Female,Cardiology,126/85,81.0,98.4,212.0,150.0,Heart Disease,Routine,6,62179.59,No,Middle Age,126,85,True,10363.265000

High Cholesterol

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
9,P04449,56.0,Male,General Medicine,102/76,83.0,97.9,263.0,147.0,Migraine,Routine,6,150822.91,No,Middle Age,102,76,True,25137.151667
20,P00800,48.0,Female,Oncology,121/74,91.0,96.9,241.0,122.0,Asthma,Emergency,3,61810.88,No,Middle Age,121,74,True,20603.626667
27,P09113,67.0,Male,Oncology,162/102,104.0,99.1,243.0,89.0,Asthma,Emergency,4,93640.46,No,Senior,162,102,True,23410.115000
30,P04443,57.0,Female,General Medicine,103/80,67.0,98.6,271.0,134.0,Fracture,Routine,6,85668.60,No,Middle Age,103,80,True,14278.100000
50,P00316,48.0,Female,Oncology,122/64,85.0,98.2,243.0,81.0,Diabetes,Routine,4,103972.31,No,Middle Age,122,64,True,25993.077500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9903,P00392,56.0,Male,Oncology,140/88,101.0,99.2,273.0,163.0,Fracture,Routine,7,126760.28,No,Middle Age,140,88,True,18108.611429
9947,P08227,40.0,Male,Neurology,101/85,78.0,97.7,280.0,146.0,Heart Disease,Routine,2,36953.04,Yes,Young Adult,101,85,True,18476.520000
9972,P09168,30.0,Female,Pediatrics,111/87,95.0,96.7,242.0,124.0,Migraine,Emergency,5,129951.01,No,Young Adult,111,87,True,25990.202000
9979,P06397,50.0,Male,Neurology,127/73,85.0,98.2,264.0,70.0,Asthma,Emergency,7,130866.79,No,Middle Age,127,73,True,18695.255714
9998,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No,Middle Age,95,83,True,25226.667500

High Heart Rate

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
6,P02996,49.0,Male,Neurology,118/83,108.0,99.4,192.0,166.0,Heart Disease,Routine,7,106428.84,No,Middle Age,118,83,True,15204.120000
11,P09211,21.0,Female,Cardiology,114/75,110.0,99.0,137.0,66.0,Fracture,Routine,6,104979.30,No,Young Adult,114,75,True,17496.550000
27,P09113,67.0,Male,Oncology,162/102,104.0,99.1,243.0,89.0,Asthma,Emergency,4,93640.46,No,Senior,162,102,True,23410.115000
130,P03317,47.0,Female,Orthopedics,126/79,101.0,99.9,195.0,169.0,Heart Disease,Emergency,3,95137.05,No,Middle Age,126,79,True,31712.350000
184,P00795,28.0,Male,Orthopedics,110/73,101.0,99.6,218.0,166.0,Migraine,Routine,9,238433.85,Yes,Young Adult,110,73,True,26492.650000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9832,P03305,67.0,Female,Orthopedics,120/81,102.0,98.0,182.0,88.0,Heart Disease,Emergency,5,57021.50,No,Senior,120,81,True,11404.300000
9841,P08902,51.0,Female,Oncology,177/73,101.0,99.7,190.0,137.0,Heart Disease,Routine,6,125527.44,No,Middle Age,177,73,True,20921.240000
9903,P00392,56.0,Male,Oncology,140/88,101.0,99.2,273.0,163.0,Fracture,Routine,7,126760.28,No,Middle Age,140,88,True,18108.611429
9931,P09468,14.0,Male,Orthopedics,118/83,110.0,99.8,124.0,77.0,Cancer,Routine,6,115100.62,No,Child,118,83,True,19183.436667
9977,P09275,36.0,Female,Oncology,120/78,102.0,98.4,202.0,82.0,Hypertension,Referral,2,65779.67,No,Young Adult,120,78,True,32889.835000